version: "3.9"
services:
  api-lib-front:
    image: api-lib-front:1.0
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - mynetwork
  mongodb:
    image: mongo:7.0-rc
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge

